### ISSUE TITLE
ImportError: No module named past.utils

### ISSUE THREAD

**Issue by maciejkurek87** [marionmari/pyGPs#36] opened 2016-10-06 00:36 UTC
C:\Python27\Lib\site-packages\pyGPs\Demo\Clustering>python demo_clustering.py
Traceback (most recent call last):
  File "demo_clustering.py", line 7, in <module>
    import pyGPs,math
  File "C:\Python27\lib\site-packages\pyGPs\__init__.py", line 2, in <module>
    from . import Optimization
  File "C:\Python27\lib\site-packages\pyGPs\Optimization\__init__.py", line 2, in <module>
    from . import scg
  File "C:\Python27\lib\site-packages\pyGPs\Optimization\scg.py", line 3, in <module>
    from past.utils import old_div
ImportError: No module named past.utils

This both happens with pip install and when doing it manually using the git repo.

Thanks!

**Comment by mathDR** [comment] 2016-10-06 16:43
This is a duplicate of #35 and that one was just fixed and closed.  Basically I had to update the setup.py file.  Note, for a quick fix, 
```python
pip install future
```
will add the required past.utils dependency

**Closed by mathDR** 2016-10-06 16:43 UTC

**Comment by Kumudaya** [comment] 2022-03-14 06:32
> This is a duplicate of #35 and that one was just fixed and closed. Basically I had to update the setup.py file. Note, for a quick fix,
> 
> ```python
> pip install future
> ```
> 
> will add the required past.utils dependency

Here is the complete [guide](https://python-future.org/quickstart.html#installation) for the installation
