### ISSUE TITLE
model.predict(z)

### ISSUE THREAD

**Issue by mahmoudaymo** [marionmari/pyGPs#34] opened 2016-09-02 13:35 UTC
Hi, my name is mahmoud and I am new to using pyGPs package.

When executing the following codes on my own data it work perfectly without erros:
model = pyGPs.GPR() 
model.getPosterior(x, y) 
model.optimize(x, y)

However, when  executing 

model.predict(z)
I get the following error TypeError: unhashable type: 'list'

TypeError                                 Traceback (most recent call last)
<ipython-input-175-7cf4f6ce44c8> in <module>()
----> 1 model.predict(z)

C:\Users\m.aymo\Anaconda2\lib\site-packages\pyGPs\Core\gp.pyc in predict(self, xs, ys)
    392         while nact<=ns-1:                              # process minibatches of test cases to save memory
    393             id  = range(nact,min(nact+nperbatch,ns))   # data points to process
--> 394             kss = covfunc.getCovMatrix(z=xs[id,:], mode='self_test')    # self-variances
    395             Ks  = covfunc.getCovMatrix(x=x[nz,:], z=xs[id,:], mode='cross')   # cross-covariances
    396             ms  = meanfunc.getMean(xs[id,:])

C:\Users\m.aymo\Anaconda2\lib\site-packages\pandas\core\frame.pyc in **getitem**(self, key)
   1990             return self._getitem_multilevel(key)
   1991         else:
-> 1992             return self._getitem_column(key)
   1993 
   1994     def _getitem_column(self, key):

C:\Users\m.aymo\Anaconda2\lib\site-packages\pandas\core\frame.pyc in _getitem_column(self, key)
   1997         # get column
   1998         if self.columns.is_unique:
-> 1999             return self._get_item_cache(key)
   2000 
   2001         # duplicate columns & possible reduce dimensionality

C:\Users\m.aymo\Anaconda2\lib\site-packages\pandas\core\generic.pyc in _get_item_cache(self, item)
   1341         """Return the cached item, item represents a label indexer."""
   1342         cache = self._item_cache
-> 1343         res = cache.get(item)
   1344         if res is None:
   1345             values = self._data.get(item)

TypeError: unhashable type: 'list'

Could you please guide me how to solve this issue,

**Comment by mathDR** [comment] 2016-09-02 14:12
Hey @mahmoudaymo can you post a full example?  That or generate x,y and z that recreate the issue?

**Comment by mahmoudaymo** [comment] 2016-09-02 16:41
i have a dataframe name df, form the df dataframe i create a train and test sets as follow:

train = df[df.Year !=2016]
test = df[df.Year == 2016]

Note that the first column is my target column which is called "prod"
x = train[train.columns[1:]]
y = train["prod"]

Finally I execute the code as follow:
model = pyGPs.GPR() 
model.getPosterior(x, y) 
model.optimize(x, y)

model.predict(test)

**Comment by mathDR** [comment] 2016-09-05 16:02
Okay, this is a guess, but it looks like you need to segment out the independent variable from test.  What happens if you run:
```python
xtest = test[test.columns[1:]]
ytest = test['prod']
model.predict(xtest)
```

**Comment by mahmoudaymo** [comment] 2016-09-05 16:12
Hi Dan,

I have already done that, but I am still getting the same problem

**Comment by mathDR** [comment] 2016-09-05 16:15
Okay, can you do this:  what is the output of 
```python
type(x)
type(xtest)
```

**Comment by mahmoudaymo** [comment] 2016-09-05 16:16
type(x) gives:
pandas.core.frame.DataFrame

type(xtest)
pandas.core.frame.DataFrame

**Comment by mathDR** [comment] 2016-09-05 16:18
What are their respective shapes?

**Comment by mahmoudaymo** [comment] 2016-09-05 16:19
x.shape: (804, 32)
xtest.shape: (116, 32)

**Comment by mathDR** [comment] 2016-09-05 16:22
Hmm, okay that works.  Could you perchance post an entire example that replicates the issue?  It is difficult to diagnose without a complete example.

**Comment by mahmoudaymo** [comment] 2016-09-05 16:27
df = pd.read_excel(Path_to_fil + filename)

test = df[df.Year == '2015-2016']
train = df[df.Year != '2015-2016']

x = train[train.columns[1:]]
y = train['prod']
xtest = test[test.columns[1:]]
ytest = test['prod']

#################

model = pyGPs.GPR()
model.getPosterior(x, y)
model.optimize(x, y)
model.predict(xtest)

**Comment by mathDR** [comment] 2016-09-05 16:48
I cannot reproduce your problem.  I tried with the mauna.txt dataset from the MaunaLoa folder.  I imported it into excel, then exported it as mauna1.xslx and ran:
```python
import numpy as np
import pandas as pd
import pyGPs

df1 = pd.read_excel('mauna1.xlsx')
df = df1[df1.C02 > 0]
train = df[df.Year < 2011]
test = df[df.Year >= 2011]

x = train['Year']
y = train['C02']
xtest = test['Year']
ytest = test['C02']

#################

model = pyGPs.GPR()
model.getPosterior(x, y)
model.optimize(x, y)
model.predict(xtest)
```
and it ran successfully.

**Comment by mathDR** [comment] 2016-09-05 16:48
Therefore, I can only conclude it must be in the way you are generating your xtest values.

**Comment by mahmoudaymo** [comment] 2016-09-05 17:08
the xtest is simply a dataframe of features that are the same features in xtrain

I am not doing and strange thing to generate the xtest values.

**Comment by mathDR** [comment] 2016-09-05 19:44
So if you run model.predict on X it works?

**Comment by mathDR** [comment] 2017-02-06 16:55
Hey @mahmoudaymo did you ever resolve this problem?  I would like to close this issue if possible

**Comment by mahmoudaymo** [comment] 2017-02-06 18:38
Yes, thank you very much.

**Closed** 2017-02-06 19:05 UTC
